name: Deploy to Amazon EC2

on:
  push:
    branches: [ "master" ] # Se ejecuta cuando subes cambios a master

jobs:
# --- JOB DE PRUEBAS ---
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # O la versión que uses

      - name: Install Dependencies
        run: |
          cd backend
          npm install

      - name: Run Tests
        run: |
          cd backend
          npm test
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/submission-ivan-emmanuel-flores-trejo
            git pull origin master
            # Crear el archivo .env desde los secretos de GitHub
            echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" > .env
            echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> .env
            # Docker compose up
            sudo docker compose up --build -d